resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master
- name: every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: build
  plan:
  - aggregate:
    - get: pet-source
      trigger: true
    - get: every-1m
      trigger: true
  - task: build
    file: pet-source/pipeline/build.yml
