resources:
- name: git-repo
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master
- name: every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: test
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: pipeline/build.yml
