resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

- name: gh-release
  type: github-release
  source:
    user: xtangle
    repository: fake-repository
    access_token: 86516b6255c92a9c359cf15616c903a800dcda71

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client.yml
  #- task: release-client
  #  file: pet-source/pipeline/release-client.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server-2.yml
  - put: gh-release
    params:
      name: pet-source/pipeline/release.txt
      tag: pet-source/pipeline/release.txt
      globs:
      - pet-source/built-pet-server/target/*.jar

- name: deploy-stage-client
  plan:
  - get: pet-source
    passed: [commit-stage-client]
    trigger: true
  - task: deploy-client
    file: pet-source/pipeline/build-client-2.yml

- name: deploy-stage-server
  plan:
  - get: pet-source
    passed: [commit-stage-server]
    trigger: true
  - task: deploy-server
    file: pet-source/pipeline/deploy-server.yml

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      passed: [deploy-stage-client, deploy-stage-server]
      trigger: true
  - task: journey-test
    file: pet-source/pipeline/journey.yml
