resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

jobs:
- name: commit-stage
  plan:
  - get: pet-source
    trigger: true
  - task: build
    file: pet-source/pipeline/build.yml

