resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

- name: cf-dev-space
  type: cf
  source:
    api: https://api.pcf-system.intware.com
    username: jacky.xu
    password: Vq7n3Jkwr
    organization: XtremeLearning
    space: concourse-dev
    skip_cert_check: true

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client.yml
  - put: cf-dev-space
    params:
      manifest: built-pet-client/deploy-client.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server.yml
  - put: cf-dev-space
    params:
      manifest: built-pet-server/deploy-server.yml

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      passed: [commit-stage-client, commit-stage-server]
      trigger: true
  - task: journey-test
    file: pet-source/pipeline/journey.yml
