resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

- name: cf-dev-space
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: jacky.xu
    password: Vq7n3Jkwr
    organization: XtremeLearning
    space: concourse-dev
    skip_cert_check: false

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client.yml
  #- task: release-client
  #  file: pet-source/pipeline/release-client.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server.yml
  - put: cf-dev-space
    params:
      manifest: pet-source/deploy-server.yml

- name: deploy-stage-client
  plan:
  - get: pet-source
    passed: [commit-stage-client]
    trigger: true
  - task: deploy-client
    file: pet-source/pipeline/build-client-2.yml

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      passed: [deploy-stage-client]
      trigger: true
  - task: journey-test
    file: pet-source/pipeline/journey.yml
