resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

jobs:
- name: commit-stage
  plan:
  - get: pet-source
    trigger: true
  #- aggregate:
  #  - task: build-server
  #    file: pet-source/pipeline/build-server.yml
  #  - task: build-client
  #    file: pet-source/pipeline/build-client.yml
  - task: journey
    file: pet-source/pipeline/journey.yml
