resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client-2.yml
  #- task: journey
  #  file: pet-source/pipeline/journey.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server-2.yml

- name: deploy-stage-client
  plan:
  - get: pet-source
    passed: [commit-stage-client]
    trigger: true
  - task: deploy-client
    file: pet-source/pipeline/build-client-2.yml

- name: deploy-stage-server
  plan:
  - get: pet-source
    passed: [commit-stage-server]
    trigger: true
  - task: deploy-server
    file: pet-source/pipeline/build-server-2.yml

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      passed: [deploy-stage-client, deploy-stage-server]
      trigger: true
  - task: journey-test
    file: pet-source/pipeline/journey.yml
