resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client.yml
  #- task: journey
  #  file: pet-source/pipeline/journey.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server.yml

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      passed: [commit-stage-client, commit-stage-server]
  - task: example
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: '7.7.4'
      run:
        path: echo
        args: ["Hello guys"]
