resources:
- name: pet-source
  type: git
  source:
    uri: https://github.com/xtangle/pet.git
    branch: master

jobs:
- name: commit-stage-client
  plan:
  - get: pet-source
    trigger: true
  - task: build-client
    file: pet-source/pipeline/build-client-2.yml
  #- task: journey
  #  file: pet-source/pipeline/journey.yml

- name: commit-stage-server
  plan:
  - get: pet-source
    trigger: true
  - task: build-server
    file: pet-source/pipeline/build-server-2.yml

#- name: deploy-stage-client


#- name: deploy-stage-server

- name: integration
  plan:
  - aggregate:
    - get: pet-source
      trigger: true
      passed: [commit-stage-client, commit-stage-server]
  - task: example
    file: pet-source/pipeline/journey.yml
